module peds_tentativa_2 {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.web;
    requires org.controlsfx.controls;
    requires org.kordamp.ikonli.javafx;
    requires org.kordamp.bootstrapfx.core;
    requires jdk.jdi;
    requires java.sql;
    requires java.compiler;
    requires org.apache.poi.poi;
    requires org.apache.poi.ooxml;
    requires javafx.graphics;
    requires javafx.base;
    requires org.apache.poi.ooxml.schemas;
    requires org.apache.xmlbeans;
    requires org.apache.commons.compress;
    requires org.apache.commons.collections4;
    requires com.google.gson;
    requires org.kordamp.ikonli.core;
    requires org.apache.commons.codec;
    requires org.apache.logging.log4j;
    exports App;
    exports Controller;
    exports Model;
    exports View;
    opens Model to com.google.gson;
    requires java.desktop;
    requires org.jsoup;
    opens Controller to javafx.fxml;
    opens View to javafx.fxml;
}
